### ISSUE TITLE
Code refactoring

### ISSUE THREAD

**Issue by tzwm** [tzwm/WeActivity#2]
Because of deadline of ImagineCup, I have written terrible code everywhere. 
We need to refactor code firstly, and then continue to write.

**Comment by tjulinfan-zz** [comment]
Got it!

Junzhe Wang notifications@github.com于2014年3月25日星期二写道：

> Because of deadline of ImagineCup, I have written terrible code
> everywhere.
> We need to refactor code firstly, and then continue to write.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/tzwm/WeActivity/issues/2
> .

## 

Best Regard & Wishes
LinFan
Google Camp
Tongji U, SSE
